/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'licons\'">' + entity + '</span>' + html;
	}
	var icons = {
		'li-accessibility': '&#xe901;',
		'li-ampersand': '&#xe902;',
		'li-anchor': '&#xe90e;',
		'li-archive': '&#xe91d;',
		'li-asterisk': '&#xe91e;',
		'li-at': '&#xe922;',
		'li-balloons': '&#xe923;',
		'li-birthday-cake': '&#xe927;',
		'li-gift': '&#xe959;',
		'li-turn-off': '&#xe9bb;',
		'li-ban': '&#xe925;',
		'li-warning': '&#xe9cb;',
		'li-bell': '&#xe92d;',
		'li-bullhorn': '&#xe92e;',
		'li-calendar': '&#xe934;',
		'li-certificate': '&#xe9a3;',
		'li-clock': '&#xe937;',
		'li-chat': '&#xe935;',
		'li-comment': '&#xe93c;',
		'li-copyright': '&#xe93e;',
		'li-registered': '&#xe99e;',
		'li-trademark': '&#xe9b7;',
		'li-delivery': '&#xe940;',
		'li-dots-h': '&#xe943;',
		'li-dots-v': '&#xe944;',
		'li-download': '&#xe945;',
		'li-envelope': '&#xe948;',
		'li-exclamation': '&#xe949;',
		'li-question': '&#xe999;',
		'li-eye': '&#xe94b;',
		'li-eye-slash': '&#xe94a;',
		'li-filter': '&#xe950;',
		'li-flag': '&#xe903;',
		'li-graduation-cap': '&#xe95c;',
		'li-hashtag': '&#xe95d;',
		'li-heart': '&#xe95f;',
		'li-home': '&#xe960;',
		'li-hourglass': '&#xe961;',
		'li-infinity': '&#xe962;',
		'li-info': '&#xe963;',
		'li-laptop': '&#xe967;',
		'li-leaf': '&#xe968;',
		'li-link': '&#xe96c;',
		'li-lock': '&#xe96f;',
		'li-unlock': '&#xe9c0;',
		'li-unlock-alt': '&#xe9bf;',
		'li-magnet': '&#xe971;',
		'li-magnet-alt': '&#xe970;',
		'li-map-marker': '&#xe973;',
		'li-menu': '&#xe97a;',
		'li-minus': '&#xe97e;',
		'li-plus': '&#xe997;',
		'li-more-or-less': '&#xe981;',
		'li-check': '&#xe936;',
		'li-close': '&#xe938;',
		'li-divide': '&#xe941;',
		'li-dollar': '&#xe942;',
		'li-percent': '&#xe98d;',
		'li-permille': '&#xe98e;',
		'li-music': '&#xe984;',
		'li-music-alt': '&#xe983;',
		'li-headphones': '&#xe95e;',
		'li-note': '&#xe986;',
		'li-options': '&#xe987;',
		'li-paper': '&#xe989;',
		'li-printer': '&#xe998;',
		'li-paper-plane': '&#xe988;',
		'li-paperclip': '&#xe98a;',
		'li-pencil': '&#xe98c;',
		'li-phone': '&#xe98f;',
		'li-mobile': '&#xe97f;',
		'li-quote-left': '&#xe99a;',
		'li-quote-right': '&#xe99b;',
		'li-quotes': '&#xe99c;',
		'li-rss': '&#xe9a1;',
		'li-search': '&#xe9a2;',
		'li-settings': '&#xe904;',
		'li-share': '&#xe9a4;',
		'li-signal': '&#xe9a6;',
		'li-wireless': '&#xe9ce;',
		'li-star': '&#xe9ad;',
		'li-tag': '&#xe9b2;',
		'li-thumbs-up': '&#xe9b6;',
		'li-thumbs-down': '&#xe9b5;',
		'li-trash': '&#xe9b9;',
		'li-trophy': '&#xe9ba;',
		'li-university': '&#xe9be;',
		'li-user': '&#xe9c1;',
		'li-users': '&#xe9c2;',
		'li-bolt': '&#xe929;',
		'li-flash': '&#xe952;',
		'li-camera': '&#xe92f;',
		'li-fruit-apple': '&#xe957;',
		'li-book': '&#xe92a;',
		'li-bookmaker': '&#xe92b;',
		'li-briefcase': '&#xe92c;',
		'li-coffee': '&#xe93b;',
		'li-compact-disc': '&#xe93d;',
		'li-drop': '&#xe946;',
		'li-drugs': '&#xe947;',
		'li-float': '&#xe954;',
		'li-glass': '&#xe95a;',
		'li-glasses': '&#xe95b;',
		'li-balance': '&#xe921;',
		'li-atom': '&#xe91f;',
		'li-kitasato': '&#xe966;',
		'li-test-tube': '&#xe9b4;',
		'li-light': '&#xe96a;',
		'li-pie-chart': '&#xe991;',
		'li-line-chart': '&#xe96b;',
		'li-cloud': '&#xe939;',
		'li-sun': '&#xe9b1;',
		'li-moon': '&#xe980;',
		'li-planet': '&#xe995;',
		'li-mouse': '&#xe982;',
		'li-map': '&#xe974;',
		'li-picture': '&#xe990;',
		'li-bike': '&#xe926;',
		'li-pin': '&#xe993;',
		'li-pin-alt': '&#xe992;',
		'li-shield': '&#xe9a5;',
		'li-skull': '&#xe9a7;',
		'li-target': '&#xe9b3;',
		'li-umbrella': '&#xe9bd;',
		'li-maximize': '&#xe978;',
		'li-minimize': '&#xe97d;',
		'li-play': '&#xe996;',
		'li-pause': '&#xe98b;',
		'li-rec': '&#xe99d;',
		'li-stop': '&#xe9b0;',
		'li-backward': '&#xe920;',
		'li-forward': '&#xe955;',
		'li-fast-backward': '&#xe94d;',
		'li-fast-forward': '&#xe94e;',
		'li-left': '&#xe969;',
		'li-right': '&#xe9a0;',
		'li-step-left': '&#xe9ae;',
		'li-step-right': '&#xe9af;',
		'li-microphone': '&#xe97c;',
		'li-video-camera': '&#xe9c5;',
		'li-volume': '&#xe9ca;',
		'li-volume-down': '&#xe9c7;',
		'li-volume-up': '&#xe9c9;',
		'li-volume-off': '&#xe9c8;',
		'li-genderless': '&#xe958;',
		'li-neuter': '&#xe985;',
		'li-female': '&#xe94f;',
		'li-male': '&#xe972;',
		'li-venus-double': '&#xe9c3;',
		'li-mars-double': '&#xe975;',
		'li-venus-mars': '&#xe9c4;',
		'li-intersex': '&#xe965;',
		'li-mars-stroke-h': '&#xe976;',
		'li-mars-stroke-v': '&#xe977;',
		'li-mercury': '&#xe97b;',
		'li-transgender': '&#xe9b8;',
		'li-apple': '&#xe90d;',
		'li-behance': '&#xe924;',
		'li-blogger': '&#xe928;',
		'li-codepen': '&#xe93a;',
		'li-facebook': '&#xe94c;',
		'li-flickr': '&#xe953;',
		'li-foursquare': '&#xe956;',
		'li-instagram': '&#xe96d;',
		'li-linkedin': '&#xe96e;',
		'li-medium': '&#xe979;',
		'li-pinterest': '&#xe994;',
		'li-skype': '&#xe9a8;',
		'li-slack': '&#xe9a9;',
		'li-spotify': '&#xe9ac;',
		'li-twitter': '&#xe9bc;',
		'li-vimeo': '&#xe9c6;',
		'li-wikipedia': '&#xe9cc;',
		'li-windows': '&#xe9cd;',
		'li-wordpress': '&#xe9cf;',
		'li-youtube': '&#xe9d0;',
		'li-angle-top': '&#xe90a;',
		'li-angle-down': '&#xe907;',
		'li-angle-left': '&#xe908;',
		'li-angle-right': '&#xe909;',
		'li-angle-double-top': '&#xe906;',
		'li-angle-double-down': '&#xe905;',
		'li-angle-double-left': '&#xe90b;',
		'li-angle-double-right': '&#xe90c;',
		'li-arrow-top': '&#xe916;',
		'li-arrow-top-right': '&#xe915;',
		'li-arrow-right': '&#xe913;',
		'li-arrow-down-right': '&#xe910;',
		'li-arrow-down': '&#xe911;',
		'li-arrow-down-left': '&#xe90f;',
		'li-arrow-left': '&#xe912;',
		'li-arrow-top-left': '&#xe914;',
		'li-arrows': '&#xe91c;',
		'li-arrows-alt': '&#xe917;',
		'li-arrows-oblique': '&#xe91a;',
		'li-arrows-oblique-alt': '&#xe919;',
		'li-arrows-h': '&#xe918;',
		'li-arrows-v': '&#xe91b;',
		'li-slide-h': '&#xe9aa;',
		'li-slide-v': '&#xe9ab;',
		'li-caret-top': '&#xe933;',
		'li-caret-down': '&#xe930;',
		'li-caret-left': '&#xe931;',
		'li-caret-right': '&#xe932;',
		'li-angles-alt': '&#xe93f;',
		'li-angles': '&#xe951;',
		'li-loading': '&#xe99f;',
		'li-restart': '&#xe900;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/li-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
